.MODEL SMALL
.STACK 100H
.386
.DATA
	STR1 DB "Hamza Iqbal$"
	STR2 DB LENGTHOF STR1 DUP(?)
	STR3 DB LENGTHOF STR1 DUP(?)
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
		ENCRYPT MACRO STR,STRR
			LOCAL L1
			MOV SI,0
			MOV CX,LENGTHOF STR1
			L1:
			MOV BL,STRR[SI]
			XOR BL,100
			MOV STR[SI],BL
			INC SI
			LOOP L1
			MOV STR[SI],'$'
		ENDM
	ENCRYPT STR2,STR1
	MOV AH,9
	MOV DX,OFFSET STR2
	INT 21H
	ENCRYPT STR3,STR2
	MOV AH,9
	MOV DX,OFFSET STR3
	INT 21H
	MOV AH,4CH
	INT 21H
	MAIN ENDP
END MAIN